version: '3.8'

services:
  kafka-producer:
    image: owen97779/pachamama-mqtt-kafka-producer
    container_name: "pachamama-mqtt-kafka-producer"
    environment:
      - MQTT-BROKER=localhost
      - MQTT-PORT=1883
      - MQTT-TOPIC=BlueIris/logins
      - MQTT-CLIENTID=Pachamama-MQTT-Kafka-Producer
      - KAFKA-BROKER=kafka0
      - KAFKA-PORT=9092
      - KAFKA-TOPIC=BlueIris-logins
      - KAFKA-PRETTY-TOPIC=BlueIris-logins-Pretty